"""Generate browser-friendly Traditional Chinese GenYo Gothic WOFF2 shards.

Requires: python -m pip install "fonttools[woff]"
"""

from __future__ import annotations

import logging
import math
from concurrent.futures import ProcessPoolExecutor
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont


ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "src/assets/font/GenYoGothic2TW-otf"
OUTPUT_DIR = ROOT / "src/assets/font/GenYoGothic2TW-shards"
CSS_PATH = ROOT / "src/styles/font/genyo-gothic.css"
SHARD_COUNT = 100

EXTRA_RANGES = (
	(0x2000, 0x206F),  # General punctuation
	(0x2E80, 0x303F),  # CJK radicals and punctuation
	(0x3100, 0x312F),  # Bopomofo
	(0x31A0, 0x31BF),  # Extended Bopomofo
	(0xFE10, 0xFE4F),  # Vertical and compatibility forms
	(0xFF00, 0xFFEF),  # Full-width and half-width forms
)


def traditional_chinese_codepoints() -> set[int]:
	codepoints: set[int] = set()
	for value in range(0x80, 0x10000):
		try:
			chr(value).encode("cp950")
		except UnicodeEncodeError:
			continue
		codepoints.add(value)

	for start, end in EXTRA_RANGES:
		codepoints.update(range(start, end + 1))

	return codepoints


def split_shards(codepoints: set[int]) -> list[list[int]]:
	ordered = sorted(codepoints)
	shard_size = math.ceil(len(ordered) / SHARD_COUNT)
	return [ordered[index : index + shard_size] for index in range(0, len(ordered), shard_size)]


def unicode_range(codepoints: list[int]) -> str:
	return f"U+{codepoints[0]:X}-{codepoints[-1]:X}"


def build_shard(task: tuple[Path, Path, list[int]]) -> None:
	source, destination, codepoints = task
	options = subset.Options()
	options.flavor = "woff2"
	options.hinting = False
	options.layout_features = ["*"]
	options.name_IDs = [0, 1, 2, 3, 4, 5, 6]
	options.name_languages = [0x0404, 0x0409]

	font = subset.load_font(str(source), options)
	subsetter = subset.Subsetter(options=options)
	subsetter.populate(unicodes=codepoints)
	subsetter.subset(font)
	subset.save_font(font, str(destination), options)


def font_face(weight: int, filename: str, codepoints: list[int]) -> str:
	return f'''@font-face {{
	font-family: "GenYo Gothic TW";
	src: url("../../assets/font/GenYoGothic2TW-shards/{filename}") format("woff2");
	font-style: normal;
	font-weight: {weight};
	font-display: swap;
	unicode-range: {unicode_range(codepoints)};
}}'''


def main() -> None:
	logging.getLogger("fontTools.subset").setLevel(logging.ERROR)
	OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

	wanted = traditional_chinese_codepoints()
	with TTFont(SOURCE_DIR / "GenYoGothic2TW-R.otf") as source_font:
		available = set(source_font.getBestCmap())
	shards = split_shards(wanted & available)

	weights = (
		(400, "R", SOURCE_DIR / "GenYoGothic2TW-R.otf"),
		(700, "B", SOURCE_DIR / "GenYoGothic2TW-B.otf"),
	)
	tasks: list[tuple[Path, Path, list[int]]] = []
	css_blocks = [
		"/* Generated by scripts/generate-genyo-subsets.py. Do not edit manually. */"
	]

	for weight, label, source in weights:
		for index, codepoints in enumerate(shards):
			filename = f"GenYoGothic2TW-{label}-{index:03}.woff2"
			tasks.append((source, OUTPUT_DIR / filename, codepoints))
			css_blocks.append(font_face(weight, filename, codepoints))

	with ProcessPoolExecutor(max_workers=4) as executor:
		list(executor.map(build_shard, tasks))

	CSS_PATH.write_text("\n\n".join(css_blocks) + "\n", encoding="utf-8")
	print(f"Generated {len(shards)} shards for each of {len(weights)} weights")
	print(f"Covered {len(available & wanted):,} Traditional Chinese code points")


if __name__ == "__main__":
	main()
